# Generated by Django on 2026-09-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteEventos",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("lugar", models.CharField(max_length=200)),
                ("fecha_hora", models.CharField(max_length=50)),
                ("responsable", models.CharField(max_length=200)),
                ("asistentes_registrados", models.IntegerField()),
                ("usuarios_asistidos", models.IntegerField()),
            ],
            options={
                "verbose_name": "Reporte de Eventos",
                "verbose_name_plural": "Reportes de Eventos",
                "db_table": "reporte_eventos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReporteUsuarios",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("matricula", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=50)),
                ("apaterno", models.CharField(max_length=50)),
                ("amaterno", models.CharField(max_length=50)),
                ("grupo", models.CharField(max_length=50)),
                ("eventos_registrados", models.IntegerField()),
                ("eventos_asistidos", models.IntegerField()),
            ],
            options={
                "verbose_name": "Reporte de Usuarios",
                "verbose_name_plural": "Reportes de Usuarios",
                "db_table": "reporte_usuarios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre del evento")),
                ("fecha_hora", models.DateTimeField(verbose_name="Fecha y hora")),
                ("lugar", models.CharField(blank=True, max_length=200, null=True, verbose_name="Lugar o auditorio")),
                ("requiere_registro", models.BooleanField(default=True, null=True, verbose_name="¿Requiere pre-registro?")),
                ("permitir_autorregistro", models.BooleanField(default=True, null=True, verbose_name="¿Permite autoregistro?")),
                ("responsable_interno", models.CharField(blank=True, max_length=200, null=True, verbose_name="Responsable interno")),
                ("responsable_externo", models.CharField(blank=True, max_length=200, null=True, verbose_name="Responsable externo")),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "db_table": "evento",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_registro", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de registro")),
                ("equipo", models.CharField(blank=True, max_length=50, null=True, verbose_name="Equipo (opcional)")),
                (
                    "evento",
                    models.ForeignKey(
                        db_column="evento_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registros",
                        to="eventos.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registros_eventos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-registro a Evento",
                "verbose_name_plural": "Pre-registros a Eventos",
                "db_table": "registro",
                "unique_together": {("evento", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_entrada", models.DateTimeField(auto_now_add=True, verbose_name="Fecha y hora de acceso")),
                (
                    "evento",
                    models.ForeignKey(
                        db_column="evento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="eventos.evento",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        db_column="registrado_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="asistencias_escaneadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias_eventos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia a Evento",
                "verbose_name_plural": "Asistencias a Eventos",
                "db_table": "asistencia",
                "unique_together": {("evento", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="ResponsableEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "evento",
                    models.ForeignKey(
                        db_column="evento_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventos.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable de Evento",
                "verbose_name_plural": "Responsables de Eventos",
                "db_table": "responsable_evento",
                "unique_together": {("evento", "usuario")},
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="asistentes_registrados",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_registrados",
                through="eventos.Registro",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="responsables",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_a_cargo",
                through="eventos.ResponsableEvento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
