# Generated by Django on 2026-09-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clave", models.CharField(max_length=20, unique=True, verbose_name="Clave")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre de la carrera")),
                ("activa", models.BooleanField(default=True, verbose_name="¿Activa?")),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "db_table": "carrera",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30, unique=True, verbose_name="Código del aula")),
                ("edificio", models.CharField(blank=True, max_length=100, null=True, verbose_name="Edificio")),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True, verbose_name="Capacidad")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aula", "Aula"),
                            ("laboratorio", "Laboratorio"),
                            ("auditorio", "Auditorio"),
                            ("taller", "Taller"),
                            ("otro", "Otro"),
                        ],
                        default="aula",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="¿Activa?")),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "db_table": "aula",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("clave", models.CharField(max_length=30, unique=True, verbose_name="Clave de materia")),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre de la asignatura")),
                ("asistencias", models.PositiveIntegerField(default=0, verbose_name="Asistencias mínimas")),
                ("horas_semana", models.PositiveIntegerField(default=0, verbose_name="Horas semanales")),
                ("periodo", models.CharField(blank=True, max_length=30, null=True, verbose_name="Periodo / Cuatrimestre")),
                ("activa", models.BooleanField(default=True, verbose_name="¿Activa?")),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        db_column="carrera_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias",
                        to="academico.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia",
                "verbose_name_plural": "Materias",
                "db_table": "materia",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("grupo", models.CharField(default="A", max_length=10, verbose_name="Grupo")),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=15,
                        verbose_name="Día de la semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                ("hora_fin", models.TimeField(verbose_name="Hora de finalización")),
                ("periodo", models.CharField(max_length=30, verbose_name="Periodo académico")),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        db_column="aula_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horarios",
                        to="academico.aula",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        db_column="materia_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="horarios",
                        to="academico.materia",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="profesor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="horarios_impartidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Clase",
                "verbose_name_plural": "Horarios de Clases",
                "db_table": "horario",
                "ordering": ["periodo", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ProfesorDisponibilidad",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=15,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("periodo", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("disponible", "Disponible"), ("no_disponible", "No disponible")],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "profesor",
                    models.ForeignKey(
                        db_column="profesor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad de Profesor",
                "verbose_name_plural": "Disponibilidades de Profesores",
                "db_table": "profesor_disponibilidad",
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("grupo", models.CharField(default="A", max_length=10)),
                ("periodo", models.CharField(max_length=30)),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "materia",
                    models.ForeignKey(
                        db_column="materia_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="inscripciones",
                        to="academico.materia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción de Alumno",
                "verbose_name_plural": "Inscripciones de Alumnos",
                "db_table": "inscripcion",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaClase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("retardo", "Retardo"),
                            ("falta", "Falta"),
                            ("justificado", "Justificado"),
                        ],
                        default="presente",
                        max_length=15,
                    ),
                ),
                (
                    "metodo",
                    models.CharField(choices=[("qr", "Código QR"), ("manual", "Manual")], default="qr", max_length=10),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        db_column="horario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="academico.horario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias_clase",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia a Clase",
                "verbose_name_plural": "Asistencias a Clases",
                "db_table": "asistencia_clase",
            },
        ),
        migrations.AddConstraint(
            model_name="horario",
            constraint=models.UniqueConstraint(
                fields=("aula", "dia_semana", "hora_inicio", "periodo"), name="uq_horario_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="profesordisponibilidad",
            constraint=models.UniqueConstraint(
                fields=("profesor", "dia_semana", "hora_inicio", "periodo"), name="uk_profesor_disp_bloque"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("usuario", "materia", "grupo", "periodo"), name="uq_inscripcion"
            ),
        ),
        migrations.AddConstraint(
            model_name="asistenciaclase",
            constraint=models.UniqueConstraint(
                fields=("horario", "usuario", "fecha"), name="uq_asistclase_sesion"
            ),
        ),
    ]
