# Generated by Django on 2026-09-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=100, verbose_name="Tipo / Módulo")),
                ("codename", models.CharField(max_length=100, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(blank=True, max_length=100, null=True, verbose_name="Nombre descriptivo")),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permiso",
                "ordering": ["tipo", "codename"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre del perfil")),
            ],
            options={
                "verbose_name": "Perfil / Rol",
                "verbose_name_plural": "Perfiles / Roles",
                "db_table": "perfil",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("username", models.CharField(max_length=50, unique=True, verbose_name="Nombre de usuario")),
                ("password", models.CharField(max_length=255, verbose_name="Contraseña")),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("superusuario", models.BooleanField(default=False, verbose_name="¿Superusuario?")),
                ("nombre", models.CharField(blank=True, max_length=50, null=True, verbose_name="Nombre(s)")),
                ("apaterno", models.CharField(blank=True, max_length=50, null=True, verbose_name="Apellido Paterno")),
                ("amaterno", models.CharField(blank=True, max_length=50, null=True, verbose_name="Apellido Materno")),
                ("email", models.EmailField(max_length=50, unique=True, verbose_name="Correo institucional")),
                ("categoria", models.CharField(blank=True, max_length=50, null=True, verbose_name="Categoría")),
                ("whatsapp", models.CharField(max_length=50, verbose_name="WhatsApp / Teléfono")),
                ("grupo", models.CharField(max_length=50, verbose_name="Grupo")),
                ("matricula", models.CharField(blank=True, max_length=50, null=True, verbose_name="Matrícula")),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
                "ordering": ["nombre", "apaterno", "amaterno"],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("token", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("expira_en", models.DateTimeField(verbose_name="Fecha de expiración")),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Recuperación",
                "verbose_name_plural": "Tokens de Recuperación",
                "db_table": "password_reset",
            },
        ),
        migrations.CreateModel(
            name="PerfilTienePermiso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "perfil",
                    models.ForeignKey(
                        db_column="perfil_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfil",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        db_column="permiso_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.permiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Perfil",
                "verbose_name_plural": "Permisos de Perfiles",
                "db_table": "perfil_tiene_permiso",
                "unique_together": {("perfil", "permiso")},
            },
        ),
        migrations.AddField(
            model_name="perfil",
            name="permisos",
            field=models.ManyToManyField(
                blank=True,
                related_name="perfiles",
                through="usuarios.PerfilTienePermiso",
                to="usuarios.permiso",
                verbose_name="Permisos asignados",
            ),
        ),
        migrations.CreateModel(
            name="UsuarioTienePerfil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "perfil",
                    models.ForeignKey(
                        db_column="perfil_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.perfil",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "db_table": "usuario_tiene_perfil",
                "unique_together": {("usuario", "perfil")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="perfiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="usuarios.UsuarioTienePerfil",
                to="usuarios.perfil",
            ),
        ),
        migrations.CreateModel(
            name="UsuarioTienePermiso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "permiso",
                    models.ForeignKey(
                        db_column="permiso_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="usuarios.permiso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso directo de Usuario",
                "verbose_name_plural": "Permisos directos de Usuarios",
                "db_table": "usuario_tiene_permiso",
                "unique_together": {("usuario", "permiso")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="permisos_directos",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="usuarios.UsuarioTienePermiso",
                to="usuarios.permiso",
            ),
        ),
    ]
